openapi: 3.0.3
info:
  title: ESET Enterprise Inspector
  description: ESET Enterprise Inspector REST API definition
  version: 1.6-oas3
externalDocs:
  url: 'https://help.eset.com/eei/latest/en-US/api.html'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UnauthorizedError:
      type: object
      properties:
        error:
          type: string
    AuthenticateRequest:
      description: >-
        Credentials to use for authentication. Set domain to "true" if this a
        domain user.
      type: object
      required:
        - username
        - password
        - domain
      properties:
        username:
          type: string
        password:
          type: string
          format: password
        domain:
          type: boolean
    AuthenticateTokenResponse:
      type: string
      example: 'eyJhbGciOi[..]ziJSUGusY5kAI'
    LocationResponse:
      type: string
      example: 'https://lab-eei-01.lab.local:443/api/v1/exclusions/5'
      format: url
    DetectionListResponse:
      type: object
      properties:
        count:
          type: integer
          nullable: true
        value:
          type: array
          items:
            type: object
            properties:
              computerId:
                type: integer
              computerName:
                type: string
                format: hostname
              computerUuid:
                type: string
                format: uuid
              creationTime:
                type: string
                format: date-time
              id:
                type: integer
              moduleId:
                type: integer
              moduleLgAge:
                type: integer
              moduleLgPopularity:
                type: integer
              moduleLgReputation:
                type: integer
                minimum: 1
                maximum: 9
              moduleName:
                type: string
              moduleSha1:
                type: string
              moduleSignatureType:
                type: integer
                enum:
                  - 60
                  - 70
                  - 75
                  - 80
                  - 90
              moduleSigner:
                type: string
              note:
                type: string
              priority:
                type: integer
                maximum: 3
              processCommandLine:
                type: string
              processId:
                type: integer
              processUser:
                type: string
              resolved:
                type: boolean
              ruleId:
                type: integer
              ruleName:
                type: string
              ruleUuid:
                type: string
                format: uuid
              severity:
                type: integer
                minimum: 1
                maximum: 3
              severityScore:
                type: integer
                maximum: 100
              threatName:
                type: string
              threatUri:
                type: string
                format: uri
              type:
                type: integer
                maximum: 8
              uuid:
                type: string
                format: uuid
    DetectionDetailsResponse:
      type: object
      properties:
        DETECTION:
          type: object
          properties:
            computerId:
              type: integer
            computerName:
              type: string
              format: hostname
            computerUuid:
              type: string
              format: uuid
            creationTime:
              type: string
              format: date-time
            event:
              type: string
            handled:
              type: integer
              enum:
                - 0
                - 1
            id:
              type: integer
            moduleFirstSeenLocally:
              type: string
              format: date-time
            moduleId:
              type: integer
            moduleLastExecutedLocally:
              type: string
              format: date-time
            moduleLgAge:
              type: integer
            moduleLgPopularity:
              type: integer
            moduleLgReputation:
              type: integer
              enum:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 9
            moduleName:
              type: string
            moduleSha1:
              type: string
            moduleSignatureType:
              type: integer
            moduleSigner:
              type: string
            note:
              type: string
            priority:
              type: integer
              enum:
                - 0
                - 1
                - 2
                - 3
            processCommandLine:
              type: string
            processId:
              type: integer
            processPath:
              type: string
            processUser:
              type: string
            resolved:
              type: boolean
            ruleName:
              type: string
            ruleUuid:
              type: string
              format: uuid
            severity:
              type: integer
            severityScore:
              type: integer
            threatName:
              type: string
            threatUri:
              type: string
              format: uri
            type:
              enum:
                - 0
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
            uuid:
              type: string
              format: uuid
    DetectionUpdateRequest:
      type: object
      properties:
        resolved:
          type: boolean
        priority:
          type: integer
          maximum: 3
        note:
          type: string
    ExecutableBlockRequest:
      type: object
      properties:
        clean:
          type: boolean
        note:
          type: string
    ExecutableUnblockRequest:
      type: object
      properties:
        note:
          type: string
    IsolateResponse:
      type: object
      properties:
        taskUuid:
          type: string
          format: uuid
    IntegrateResponse:
      $ref: '#/components/schemas/IsolateResponse'
    RuleListResponse:
      type: object
      properties:
        count:
          type: integer
          nullable: true
        value:
          type: array
          items:
            type: object
            properties:
              enabled:
                type: boolean
              id:
                type: integer
              name:
                type: string
              severity:
                type: integer
                enum:
                  - 1
                  - 2
                  - 3
              severityScore:
                type: integer
                maximum: 100
    RuleDetailsResponse:
      type: object
      properties:
        RULE:
          type: object
          properties:
            body:
              type: string
              format: xml
            enabled:
              type: boolean
            id:
              type: integer
            name:
              type: string
            severity:
              type: integer
              enum:
                - 1
                - 2
                - 3
            severityScore:
              type: integer
              maximum: 100
            uuid:
              type: string
              format: uuid
    RuleCreateRequest:
      type: object
      xml:
        name: rule
      properties:
        definition:
          type: object
          properties:
            ancestor:
              type: object
              properties:
                distance:
                  type: integer
                  minimum: 1
                  xml:
                    attribute: true
                unique:
                  type: boolean
                  xml:
                    attribute: true
            parentprocess:
              type: object
            process:
              type: object
            operations:
              type: object
              properties:
                operation:
                  type: object
                  properties:
                    type:
                      type: string
                      xml:
                        attribute: true
        description:
          type: object
          properties:
            name:
              type: string
            category:
              type: string
            explanation:
              type: string
            os:
              type: string
              enum:
                - Windows
                - OSX
                - ANY
            mitreattackid:
              type: string
            maliciousCauses:
              type: string
            benignCauses:
              type: string
            recommendedActions:
              type: string
        actions:
          type: object
          properties:
            action:
              type: object
              properties:
                name:
                  type: string
                  xml:
                    attribute: true
                  enum:
                    - TriggerDetection
                    - MarkAsScript
                    - MarkAsCompromised
                    - HideCommandLine
                    - BlockProcessExecutable
                    - CleanAndBlockProcessExecutable
                    - BlockParentProcessExecutable
                    - CleanAndBlockParentProcessExecutable
                    - IsolateFromNetwork
                    - DropEvent
    RuleCreateResponse:
      type: object
      properties:
        body:
          type: string
          format: xml
        enabled:
          type: boolean
        id:
          type: integer
        name:
          type: string
        severity:
          type: integer
          enum:
          - 1
          - 2
          - 3
        severityScore:
          type: integer
          maximum: 100
        uuid:
          type: string
          format: uuid
    RuleUpdateRequest:
      type: object
      required:
        - enabled
      properties:
        enabled:
          type: boolean
    ExclusionCreateRequest:
      type: object
      required:
      - body
      - autoResolve
      - name
      properties:
        body:
          type: string
          format: xml
        autoResolve:
          type: boolean
        name:
          type: string
        ruleIds:
          type: array
          items:
            type: integer
        ruleUuids:
          type: array
          items:
            type: string
            format: uuid
        note:
          type: string
    ExclusionListResponse:
      type: object
      properties:
        count:
          type: integer
          nullable: true
        value:
          type: array
          items:
            type: object
            properties:
              enabled:
                type: boolean
              id:
                type: integer
              name:
                type: string
              note:
                type: string
              uuid:
                type: string
                format: uuid
    ExclusionDetailsResponse:
      type: object
      properties:
        EXCLUSION:
          type: object
          properties:
            body:
              type: string
              format: xml
            enabled:
              type: boolean
            id:
              type: integer
            name:
              type: string
            note:
              type: string
            ruleIds:
              type: array
              items:
                type: integer
            ruleUuids:
              type: array
              items:
                type: string
                format: uuid
            uuid:
              type: string
              format: uuid
    ExclusionByRuleResponse:
      type: array
      items:
        type: integer
  headers:
    X-Security-Token:
      description: Authentication token
      schema:
        $ref: '#/components/schemas/AuthenticateTokenResponse'
    Location:
      description: Location of resource
      schema:
        $ref: '#/components/schemas/LocationResponse'
  examples:
    AuthenticateRequest:
      value:
        username: Administrator
        password: eraadmin
        domain: false
    DetectionsResponse:
      value:
        value:
          - computerId: 73
            computerName: lab-ex-01.lab.local
            computerUuid: f52b4226-e90a-41e7-add9-0e92a8c97d6d
            creationTime: '2020-08-14T17:22:02Z'
            id: 100
            moduleId: 24
            moduleLgAge: 731
            moduleLgPopularity: 7
            moduleLgReputation: 9
            moduleName: netsh.exe
            moduleSha1: DCB637AF92C54162721F1E84CA59D16603FEAB2C
            moduleSignatureType: 90
            moduleSigner: Microsoft Windows
            note: ''
            priority: 0
            processCommandLine: interface tcp show global
            processId: 10000001488
            processUser: nt authority\system
            resolved: true
            ruleId: 552
            ruleName: 'System Network Configuration Discovery [F1108a]'
            ruleUuid: d971113d-c9db-44f2-8d6f-bd93564e76d0
            severity: 1
            severityScore: 13
            threatName: ''
            threatUri: ''
            type: 1
            uuid: 14e07368-ce4e-4497-b5a0-31672021d526
    RulesResponse:
      value:
        count: 2
        value:
          - enabled: true
            id: 233
            name: 'Silent execution of PsExec [B0903]'
            severity: 3
            severityScore: 81
          - enabled: true
            id: 234
            name: 'Clearing event logs [B1001]'
            severity: 3
            severityScore: 82
    RuleResponse:
      value:
        RULE:
          body: >-
            <?xml version="1.0"
            encoding="utf-8"?><rule><description><os>Windows</os><mitreattackid/><explanation/><maliciousCauses/><benignCauses/><recommendedActions/><name>Script
            interpreters detection (PowerShell/wscript)
            [X9901]</name><category>Special/system
            rules</category><guid>3FF756E1-6B54-4729-AE0D-318181D751A5</guid></description><definition><process><operator
            type="OR"><condition component="FileItem" property="FileName"
            condition="is" value="wscript.exe"/><condition component="FileItem"
            property="FileName" condition="is"
            value="powershell.exe"/><condition component="Module"
            property="OriginalFileName" condition="starts"
            value="wscript.exe"/><condition component="Module"
            property="OriginalFileName" condition="starts"
            value="powershell.exe"/></operator></process></definition><action>MarkAsScript</action></rule>
          enabled: true
          id: 594
          name: 'Script interpreters detection (PowerShell/wscript) [X9901]'
          severity: 2
          severityScore: 60
          uuid: 3ff756e1-6b54-4729-ae0d-318181d751a5
    UpdateRule:
      value:
        enabled: false
    RuleCreateRequest:
      value: |
        <?xml version="1.0" encoding="UTF-8"?>
        <rule>
            <definition>
                <ParentProcess>
                    <condition component="FileItem" condition="is" property="FileName" value="svchost.exe" />
                </ParentProcess>
                <process>
                    <operator type="AND">
                        <condition component="FileItem" condition="is" property="FileName" value="w3wp.exe" />
                        <!-- IIS worker process-->
                        <operator type="OR">
                            <condition component="FileItem" property="Path" condition="is" value="%SYSTEM%\inetsrv\" />
                            <condition component="FileItem" property="Path" condition="is" value="%WINDIR%\syswow64\inetsrv\" />
                        </operator>
                        <condition component="ProcessInfo" property="CommandLine" condition="contains" value="-ap &quot;MSExchangeECPAppPool&quot;" />
                    </operator>
                </process>
                <operations>
                    <operation type="Scripts">
                        <operator type="AND">
                            <condition component="Scripts" property="script" condition="contains" value="[Microsoft.Exchange.Data.Fqdn]" />
                            <operator type="OR">
                                <condition component="Scripts" property="script" condition="contains" value=".ForwardHelpTargetName Get-OabVirtualDirectory" />
                                <condition component="Scripts" property="script" condition="contains" value=".ForwardHelpTargetName Set-OabVirtualDirectory" />
                                <condition component="Scripts" property="script" condition="contains" value=".ForwardHelpTargetName Remove-OabVirtualDirectory" />
                            </operator>
                        </operator>
                    </operation>
                </operations>
            </definition>
            <description>
                <name>Outlook Web Access - OABVirtualDirectory Manipulation [E1802E]</name>
                <severity>70</severity>
                <explanation>This rule looks for signs that SSRF has been succesfully exploited on a Microsoft Exchange server.</explanation>
                <maliciousCauses>Succesful exploitation of CVE-2021-26855 (ProxyLogon).</maliciousCauses>
                <benigncauses>An administrator updating the OAB Virtual Directory.</benigncauses>
                <category>Exploitation</category>
            </description>
        </rule>
    RuleCreateResponse:
      value:
        RULE:
          body: >-
            <?xml version="1.0" encoding="utf-8"?><rule><definition><ParentProcess><condition component="FileItem" condition="is" property="FileName" value="svchost.exe"/>
            </ParentProcess><process><operator type="AND"><condition component="FileItem" condition="is" property="FileName" value="w3wp.exe"/><!-- IIS worker process-->
            <operator type="OR"><condition component="FileItem" property="Path" condition="is" value="%SYSTEM%inetsrv"/>
            <condition component="FileItem" property="Path" condition="is" value="%WINDIR%syswow64inetsrv"/>
            </operator><condition component="ProcessInfo" property="CommandLine" condition="contains" value="-ap &quot;MSExchangeECPAppPool&quot;"/></operator></process>
            <operations><operation type="Scripts"><operator type="AND"><condition component="Scripts" property="script" condition="contains" value="[Microsoft.Exchange.Data.Fqdn]"/>
            <operator type="OR"><condition component="Scripts" property="script" condition="contains" value=".ForwardHelpTargetName Get-OabVirtualDirectory"/>
            <condition component="Scripts" property="script" condition="contains" value=".ForwardHelpTargetName Set-OabVirtualDirectory"/>
            <condition component="Scripts" property="script" condition="contains" value=".ForwardHelpTargetName Remove-OabVirtualDirectory"/>
            </operator></operator></operation></operations></definition><description><name>Outlook Web Access - OABVirtualDirectory Manipulation [E1802E]</name>
            <severity>70</severity><explanation>This rule looks for signs that SSRF has been succesfully exploited on a Microsoft Exchange server.</explanation>
            <maliciousCauses>Succesful exploitation of CVE-2021-26855 (ProxyLogon).</maliciousCauses><benigncauses>An administrator updating the OAB Virtual Directory.
            </benigncauses><category>Exploitation</category></description></rule>
          enabled: true
          id: 954
          name: 'Outlook Web Access - OABVirtualDirectory Manipulation [E1802E]'
          severity: 2
          severityScore: 70
          uuid: da67bd31-a21d-4f1b-badb-5f6251600ef0
    DetectionUpdate:
      value:
        resolved: true
        priority: 0
        note: False positive
    ExecutableBlock:
      value:
        clean: true
        note: Ransomware
    ExecutableUnblock:
      value:
        note: 'Investigated, clean'
    ExclusionsResponse:
      value:
        count: 2
        value:
          - enabled: false
            id: 9
            name: 'Adobe, Creative Cloud - [A0103b]'
            note: >-
              Adobe Cloud Experience regularly modifies its AutoStart registry
              key
            uuid: 5d029677-276d-4a4c-8c40-1e8e7aaa6d95
          - enabled: true
            id: 16
            name: 'Rapid7 - [E1108]'
            note: Exclude reads of Firefox credentials files by Rapid7 IR agent
            uuid: 3d427e19-475f-4e0c-a813-420fc6d979f6
    ExclusionResponse:
      value:
        EXCLUSION:
          body: |
            <?xml version="1.0" encoding="utf-8"?>
            <rule>
              <description>
                <name>QEMU - [E0502]</name>
                <explanation>Exclusion for: Unpopular process makes HTTP request to a popular Web Service [E0502] - Exclude request made by QEMU</explanation>
                <category>Exclusion</category>
              </description>
              <definition>
                <process>
                  <operator type="AND">
                    <condition component="Module" property="SignatureType" condition="greaterOrEqual" value="60" />
                    <condition component="FileItem" property="FileName" condition="is" value="qemu-system-x86_64.exe" />
                    <condition component="Module" property="SignerName" condition="is" value="Stefan Weil" />
                  </operator>
                </process>
              </definition>
            </rule>
          enabled: true
          id: 5
          name: 'QEMU - [E0502]'
          note: >-
            Exclude request made by QEMU - similar to virtualbox/vmware/other
            virtualization applications
          ruleIds:
            - 391
          ruleUuids:
            - 651d6f43-5ce0-4d1b-b5da-97901f7ae01b
          uuid: 8cc989e2-578a-4b11-ba17-adbb4d9bc189
    ExclusionByRuleResponse:
      value:
        - 90
    ExclusionCreateRequest:
      value:
        body: |
            <?xml version="1.0" encoding="utf-8"?>
            <rule>
              <description>
                <name>QEMU - [E0502]</name>
                <explanation>Exclusion for: Unpopular process makes HTTP request to a popular Web Service [E0502] - Exclude request made by QEMU</explanation>
                <category>Exclusion</category>
              </description>
              <definition>
                <process>
                  <operator type="AND">
                    <condition component="Module" property="SignatureType" condition="greaterOrEqual" value="60" />
                    <condition component="FileItem" property="FileName" condition="is" value="qemu-system-x86_64.exe" />
                    <condition component="Module" property="SignerName" condition="is" value="Stefan Weil" />
                  </operator>
                </process>
              </definition>
            </rule>
        autoResolve: true
        name: 'QEMU - [E0502]'
        ruleIds:
          - 391
        ruleUuids:
          - 651d6f43-5ce0-4d1b-b5da-97901f7ae01b
        note: >-
          Exclude request made by QEMU - similar to virtualbox/vmware/other
          virtualization applications
  requestBodies:
    Authenticate:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthenticateRequest'
          examples:
            AuthenticateRequest:
              $ref: '#/components/examples/AuthenticateRequest'
    UpdateRule:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RuleUpdateRequest'
          examples:
            UpdateRule:
              $ref: '#/components/examples/UpdateRule'
    DetectionUpdate:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DetectionUpdateRequest'
    ExecutableBlock:
      required: false
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExecutableBlockRequest'
          examples:
            ExecutableBlock:
              $ref: '#/components/examples/ExecutableBlock'
    ExecutableUnblock:
      required: false
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExecutableUnblockRequest'
          examples:
            ExecutableUnblock:
              $ref: '#/components/examples/ExecutableUnblock'
    ExclusionCreate:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExclusionCreateRequest'
          examples:
            ExclusionCreate:
              $ref: '#/components/examples/ExclusionCreateRequest'
    RuleCreate:
      required: true
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/RuleCreateRequest'
          examples:
            RuleCreate:
              $ref: '#/components/examples/RuleCreateRequest'
  responses:
    UnauthorizedError:
      description: Credentials or access token missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
    ForbiddenError:
      description: Insufficient permissions to perform action
    NoContent:
      description: No content
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
    Authenticate:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
    Detections:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DetectionListResponse'
          examples:
            DetectionsResponse:
              $ref: '#/components/examples/DetectionsResponse'
    Detection:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DetectionDetailsResponse'
    Isolate:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IsolateResponse'
    Integrate:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IntegrateResponse'
    Rules:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RuleListResponse'
          examples:
            RulesResponse:
              $ref: '#/components/examples/RulesResponse'
    Rule:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RuleDetailsResponse'
          examples:
            RuleResponse:
              $ref: '#/components/examples/RuleResponse'
    RuleCreate:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RuleCreateResponse'
          examples:
            RuleCreateResponse:
              $ref: '#/components/examples/RuleCreateResponse'
    Exclusions:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExclusionListResponse'
          examples:
            RulesResponse:
              $ref: '#/components/examples/ExclusionsResponse'
    ExclusionCreate:
      description: Created
      headers:
        Location:
          $ref: '#/components/headers/Location'
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExclusionDetailsResponse'
          examples:
            ExclusionResponse:
              $ref: '#/components/examples/ExclusionResponse'
    ExclusionGet:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExclusionDetailsResponse'
          examples:
            ExclusionResponse:
              $ref: '#/components/examples/ExclusionResponse'
    ExclusionsByRule:
      description: OK
      headers:
        X-Security-Token:
          $ref: '#/components/headers/X-Security-Token'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExclusionByRuleResponse'
          examples:
            ExclusionByRuleResponse:
              $ref: '#/components/examples/ExclusionByRuleResponse'
  parameters:
    PaginationTop:
      name: $top
      description: >-
        system query option requests the number of items in the queried
        collection to be included in the result
      in: query
      allowEmptyValue: false
      required: false
      schema:
        type: integer
    PaginationSkip:
      name: $skip
      description: >-
        system query option requests the number of items in the queried
        collection that are to be skipped and not included in the result
      in: query
      allowEmptyValue: false
      required: false
      schema:
        type: integer
    PaginationCount:
      name: $count
      description: >-
        system query option allows clients to request a count of the matching
        resources included with the resources in the response. if set to
        $count=1, the number of detections is returned.
      in: query
      allowEmptyValue: false
      required: false
      schema:
        type: integer
        enum:
          - 0
          - 1
    PaginationOrderBy:
      name: $orderBy
      description: >-
        system query option allows clients to request resources in either
        ascending order using asc or descending order using desc. If not
        specified the order is in ascending way
      in: query
      allowEmptyValue: false
      required: false
      schema:
        type: string
    PaginationFilter:
      name: $filter
      description: >-
        system query option allows clients to filter a collection of resources
        that are addressed by a request URL. The query supports the following
        operators eq, ne, gt, ge, lt, le, and, or, and (). Operators can be
        combined with values to filter data. For instance, “resolved eq 0” will
        report only unresolved detections.
      in: query
      allowEmptyValue: false
      required: false
      schema:
        type: string
    IdOrUuid:
      name: id
      description: ID or UUID
      in: path
      required: true
      schema:
        type: string
    IdTypeUuid:
      name: $idType
      description: 'if $idType=uuid {id} in URL is interpreted as uuid'
      in: query
      required: false
      allowEmptyValue: false
      schema:
        type: string
        enum:
          - uuid
    IdOrSha1:
      name: id
      description: ID or SHA1
      in: path
      required: true
      schema:
        type: string
    IdTypeSha1:
      name: $idType
      description: 'if $idType=sha1 {id} in URL is interpreted as SHA1'
      in: query
      required: false
      allowEmptyValue: false
      schema:
        type: string
        enum:
          - sha1
    ComputerIdOrUuid:
      name: computerId
      description: Computer ID or UUID
      in: path
      required: true
      schema:
        type: string
    ExclusionIdOrUuid:
      name: exclusionId
      description: Exclusion ID or UUID
      in: path
      required: true
      schema:
        type: string
    RuleIdOrUuid:
      name: ruleId
      description: Rule ID or UUID
      in: path
      required: true
      schema:
        type: string
security:
  - bearerAuth: []
servers:
  - url: 'https://{baseUrl}'
    variables:
      baseUrl:
        default: eei.example.com
        description: The Enterprise Inspector base URL.
paths:
  /api/v1/authenticate:
    put:
      operationId: authenticatePut
      tags:
        - Authentication
      summary: Authentication
      description: Authenticate
      security: []
      requestBody:
        $ref: '#/components/requestBodies/Authenticate'
      responses:
        '200':
          $ref: '#/components/responses/Authenticate'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      operationId: authenticatePost
      tags:
        - Authentication
      summary: Authentication
      description: Authenticate
      security: []
      requestBody:
        $ref: '#/components/requestBodies/Authenticate'
      responses:
        '200':
          $ref: '#/components/responses/Authenticate'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /api/v1/detections:
    get:
      operationId: listDetections
      tags:
        - Detections
      summary: List of detections
      parameters:
        - $ref: '#/components/parameters/PaginationTop'
        - $ref: '#/components/parameters/PaginationSkip'
        - $ref: '#/components/parameters/PaginationCount'
        - $ref: '#/components/parameters/PaginationOrderBy'
        - $ref: '#/components/parameters/PaginationFilter'
      responses:
        '200':
          $ref: '#/components/responses/Detections'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  '/api/v1/detections/{id}':
    get:
      operationId: getDetectionDetails
      tags:
        - Detections
      summary: Get detection details
      parameters:
        - $ref: '#/components/parameters/IdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      responses:
        '200':
          $ref: '#/components/responses/Detection'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    patch:
      operationId: updateDetection
      tags:
        - Detections
      summary: Update detection
      parameters:
        - $ref: '#/components/parameters/IdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectionUpdateRequest'
            examples:
              DetectionUpdate:
                $ref: '#/components/examples/DetectionUpdate'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  '/api/v1/executables/{id}/block':
    post:
      operationId: blockExecutable
      tags:
        - Remediation
      summary: Block an executable
      parameters:
        - $ref: '#/components/parameters/IdOrSha1'
        - $ref: '#/components/parameters/IdTypeSha1'
      requestBody:
        $ref: '#/components/requestBodies/ExecutableBlock'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
  '/api/v1/executables/{id}/unblock':
    post:
      operationId: unblockExecutable
      tags:
        - Remediation
      summary: Unblock an executable
      parameters:
        - $ref: '#/components/parameters/IdOrSha1'
        - $ref: '#/components/parameters/IdTypeSha1'
      requestBody:
        $ref: '#/components/requestBodies/ExecutableUnblock'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
  '/api/v1/machines/{computerId}/isolate':
    post:
      operationId: isolateComputer
      tags:
        - Computers
      summary: Isolate a computer from the network
      parameters:
        - $ref: '#/components/parameters/ComputerIdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      responses:
        '200':
          $ref: '#/components/responses/Isolate'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
  '/api/v1/machines/{computerId}/integrate':
    post:
      operationId: integrateComputer
      tags:
        - Computers
      summary: Integrate a computer back into the network
      parameters:
        - $ref: '#/components/parameters/ComputerIdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      responses:
        '200':
          $ref: '#/components/responses/Integrate'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
  /api/v1/rules:
    get:
      operationId: listRules
      tags:
        - Rules
      summary: List rules
      parameters:
        - $ref: '#/components/parameters/PaginationTop'
        - $ref: '#/components/parameters/PaginationSkip'
        - $ref: '#/components/parameters/PaginationCount'
        - $ref: '#/components/parameters/PaginationOrderBy'
        - $ref: '#/components/parameters/PaginationFilter'
      responses:
        '200':
          $ref: '#/components/responses/Rules'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      operationId: createRule
      tags:
        - Rules
      summary: Creates a new rule
      requestBody:
        $ref: '#/components/requestBodies/RuleCreate'
      responses:
        '200':
          $ref: '#/components/responses/RuleCreate'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  '/api/v1/rules/{id}':
    get:
      operationId: getRuleDetails
      tags:
        - Rules
      summary: Gets a single rule
      parameters:
        - $ref: '#/components/parameters/IdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      responses:
        '200':
          $ref: '#/components/responses/Rule'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
    put:
      operationId: editRule
      tags:
        - Rules
      summary: Edits rule body
      parameters:
        - $ref: '#/components/parameters/IdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      responses:
        '200':
          $ref: '#/components/responses/Rule'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
    delete:
      operationId: deleteRule
      tags:
        - Rules
      summary: Deletes a rule
      parameters:
        - $ref: '#/components/parameters/IdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
    patch:
      operationId: updateRule
      tags:
        - Rules
      summary: Updates particular rule
      parameters:
        - $ref: '#/components/parameters/IdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      requestBody:
        $ref: '#/components/requestBodies/UpdateRule'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
  /api/v1/exclusions:
    get:
      operationId: listExclusions
      tags:
        - Exclusions
      summary: List exclusions
      parameters:
        - $ref: '#/components/parameters/PaginationTop'
        - $ref: '#/components/parameters/PaginationSkip'
        - $ref: '#/components/parameters/PaginationCount'
        - $ref: '#/components/parameters/PaginationOrderBy'
        - $ref: '#/components/parameters/PaginationFilter'
      responses:
        '200':
          $ref: '#/components/responses/Exclusions'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      operationId: createExclusion
      tags:
        - Exclusions
      summary: Creates a new exclusion
      requestBody:
        $ref: '#/components/requestBodies/ExclusionCreate'

      responses:
        '201':
          $ref: '#/components/responses/ExclusionCreate'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  '/api/v1/exclusions/{exclusionId}':
    get:
      operationId: getExclusionDetails
      tags:
        - Exclusions
      summary: Gets a single exclusion
      parameters:
        - $ref: '#/components/parameters/ExclusionIdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      responses:
        '200':
          $ref: '#/components/responses/ExclusionGet'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    put:
      operationId: editExclusion
      tags:
        - Exclusions
      summary: Edits exclusion body
      parameters:
        - $ref: '#/components/parameters/ExclusionIdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      requestBody:
        $ref: '#/components/requestBodies/ExclusionCreate'
      responses:
        '200':
          $ref: '#/components/responses/ExclusionCreate'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      operationId: deleteExclusion
      tags:
        - Exclusions
      summary: Deletes an exclusion
      parameters:
        - $ref: '#/components/parameters/ExclusionIdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  '/api/v1/exclusions/rule/{ruleId}':
    get:
      operationId: getExclusionsByRule
      tags:
        - Exclusions
      summary: Get exclusions associated with a rule
      parameters:
        - $ref: '#/components/parameters/RuleIdOrUuid'
        - $ref: '#/components/parameters/IdTypeUuid'
      responses:
        '200':
          $ref: '#/components/responses/ExclusionsByRule'
        '401':
          $ref: '#/components/responses/UnauthorizedError'